# For a description of these parameters, please visit the theme wiki.
# https://github.com/pacollins/hugo-future-imperfect-slim/wiki/config.toml
baseurl                 = "https://quancs.github.io/"
DefaultContentLanguage  = "en"
title                   = "Changsheng Quan"
theme                   = "hugo-future-imperfect-slim"
paginate                = 3
disqusShortname         = ""
googleAnalytics         = ""
pluralizeListTitles     = false
disableLanguages        = []
ignoreErrors = ["error-remote-getjson"]

[markup.goldmark.renderer]
  unsafe                = true

[module]
  [module.hugoVersion]
  extended              = true
  min                   = "0.62.0"

[outputs]
  home                  = ["html", "json", "rss"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = ""
  highlightjsLang       = []
  viewMorePostsLink     = "blog"
  readingTime           = true
  imageStretch          = ""
  removeBlur            = false
  # socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
  hideEmptyStats        = true
  toc                   = false
  tocWords              = 400

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "HTML5UP and Hugo"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Home"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = false
    languageMenu        = true

  [params.intro]
    header                = "Changsheng Quan"
    paragraph             = "A PhD Student of Computer Science"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/logo.jpg"
      shape               = "circle"
      width               = ""
      alt                 = "Changsheng Quan's Photo"

  [params.sidebar]
    # about               = "This theme was developed for Hugo static site generator."
    postAmount          = 5
    categories          = false
    categoriesByCount   = true

  # [params.footer]
  #   rssFooter           = true
  #   socialFooter        = true

  [params.utterances]
    enabled             = false
    repo                = ""
    issueTerm           = "pathname"
    issueNumber         = ""
    label               = ""
    theme               = "github-light"

  # [params.staticman]
  #   enabled             = true
  #   api                 = ""  # No Trailing Slash
  #   gitProvider         = ""
  #   username            = ""
  #   repo                = ""
  #   branch              = ""

  #   [params.staticman.recaptcha]
  #     siteKey           = ""
  #     encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = ""
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About Me"
    identifier        = "about"
    url               = "about"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "blog"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  # [[menu.main]]
  #   name              = "Categories"
  #   identifier        = "categories"
  #   url               = "categories"
  #   pre               = "<i class='fas fa-sitemap'></i>"
  #   weight            = 5

  [[menu.main]]
    name              = "Contact"
    identifier        = "contact"
    url               = "contact"
    pre               = "<i class='far fa-envelope'></i>"
    weight            = 6

  [[menu.main]]
    name              = "Publication"
    identifier        = "publication"
    url               = "publication"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 7

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

  [Languages.zh-CN]
    LanguageCode        = "zh-CN"
    LanguageName        = "中文 (简体)"
    # title               = "失败乃成功之母"
    # description         = "中文 (简体) 描述"
    weight              = 2

    [[Languages.zh-CN.menu.main]]
      name              = "主页"
      identifier        = "home"
      url               = ""
      pre               = "<i class='fas fa-home'></i>"
      weight            = 1

    [[Languages.zh-CN.menu.main]]
      name              = "关于我"
      identifier        = "about"
      url               = "about"
      pre               = "<i class='far fa-id-card'></i>"
      weight            = 2

    [[Languages.zh-CN.menu.main]]
      name              = "博客"
      identifier        = "blog"
      url               = "blog"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 3

    # [[Languages.zh-CN.menu.main]]
    #   name              = "类别"
    #   identifier        = "categories"
    #   url               = "categories"
    #   pre               = "<i class='fas fa-sitemap'></i>"
    #   weight            = 5

    [[Languages.zh-CN.menu.main]]
      name              = "联系方式"
      identifier        = "contact"
      url               = "contact"
      pre               = "<i class='far fa-envelope'></i>"
      weight            = 6

    [[Languages.zh-CN.menu.main]]
      name              = "发表文献"
      identifier        = "publication"
      url               = "publication"
      pre               = "<i class='far fa-newspaper'></i>"
      weight            = 7

    [Languages.zh-CN.params.intro]
      header                = "全昌盛"
      paragraph             = "一名<a href='https://www.westlake.edu.cn'>计算机科学专业</a>的博士研究生"
      rssIntro              = true
      socialIntro           = true
      hideWhenSingleColumn  = true
      alwaysOnHomepage      = false

      [Languages.zh-CN.params.intro.pic]
        src                 = "img/main/logo.jpg"
        shape               = "circle"
        width               = ""
        alt                 = "Changsheng Quan's Photo"

    
    [Languages.zh-CN.params.header]
      navbarTitle         = "主页"
      dynamicTitles       = true
      searchMenu          = true
      shareMenu           = false
      languageMenu        = true


[social]
  # Coding Communities
  github                = "quancs"
#   gitlab                = ""
#   stackoverflow         = "" # User Number
#   bitbucket             = ""
#   jsfiddle              = ""
#   codepen               = ""
  # Visual Art Communities
#   deviantart            = ""
#   flickr                = "example"
#   behance               = ""
#   dribbble              = ""
  # Publishing Communities
#   wordpress             = ""
#   medium                = ""
  # Professional/Business Oriented Communities
#   linkedin              = "example"
#   linkedin_company      = "examplebusiness"
#   foursquare            = ""
#   xing                  = ""
#   slideshare            = ""
  # Social Networks
#   facebook              = "example"
#   googleplus            = ""
#   reddit                = "example"
#   quora                 = ""
#   youtube               = ""
#   vimeo                 = ""
#   whatsapp              = "" # WhatsApp Number
    # WeChat and QQ need testing.
    # wechat              = ""
    qq                  = "1017241746" # User ID Number
#   instagram             = "example"
#   tumblr                = ""
#   twitter               = "example"
#   strava                = ""
#   skype                 = ""
#   snapchat              = ""
#   pinterest             = "example"
#   telegram              = "example"
#   vine                  = ""
  googlescholar         = "prTK3NwAAAAJ"
#   orcid                 = ""
#   researchgate          = "example"
#   keybase               = "example"
#   mastodon              = "example.com/@example"
  # Email
  email                 = "quancs@qq.com"
